edition = "2021"
# Basic
hard_tabs = true
max_width = 100
use_small_heuristics = "Max"
# Consistency
newline_style = "Unix"
# Misc
chain_width = 80
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
use_field_init_shorthand = true

# Imports
reorder_imports = true

#require unstable

# Format comments
comment_width = 100
wrap_comments = true

# Imports
imports_granularity = "Crate"

# Misc
reorder_impl_items = false
spaces_around_ranges = false
binop_separator = "Back"
match_arm_blocks = false
trailing_semicolon = false
trailing_comma = "Vertical"
